import { randomUUID } from "node:crypto";
import { execFile } from "node:child_process";
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { promisify } from "node:util";
import { ImplementationPlanSchema, ReviewDecisionSchema, SiteBriefSchema, SiteSpecificationSchema, TestReportSchema, type WorkflowState } from "@wp-agent-studio/shared";
import type { StructuredAgentProvider } from "@wp-agent-studio/agent-providers";
import { generateBlockTheme } from "@wp-agent-studio/wordpress";
import { automaticNextState, assertTransition, isTerminalState, isWaitingState } from "./state-machine.js";
import { writeProjectMemoryFiles } from "./memory-files.js";

export type RunData = { id: string; projectId: string; workspaceId: string; state: WorkflowState; stateVersion: number; isPaused: boolean; cancellationRequested: boolean; turnCount: number; fixCycleCount: number; maxTurns: number; maxFixCycles: number; brief: unknown; specification?: unknown; plan?: unknown; review?: unknown; testReport?: unknown; workspaceDirectory: string; target: "local" | "remote" };
export interface WorkflowRepository {
  getRun(runId: string): Promise<RunData>; transition(runId: string, expectedVersion: number, to: WorkflowState, audit: { action: string; correlationId: string }): Promise<RunData>;
  patchRun(runId: string, patch: Partial<RunData>): Promise<RunData>; addMessage(run: RunData, message: { sender: "claude" | "codex" | "system"; recipient: "claude" | "codex" | "user" | "all"; type: string; content: string; payload: unknown; parentMessageId?: string }): Promise<string>;
  addUsage(runId: string, agent: "claude" | "codex", usage: unknown): Promise<void>; requestApproval(run: RunData, kind: "PLAN" | "DEPLOYMENT", summary: string, changes: unknown): Promise<void>;
  saveArtifact(run: RunData, artifact: { kind: string; name: string; path: string; sha256: string; size: number }): Promise<void>;
  deployStaging(run: RunData): Promise<{ success: boolean; message: string; exactResponses: unknown[] }>;
  captureWordPressSnapshot(run: RunData): Promise<unknown>;
}

export class WorkflowEngine {
  constructor(private readonly repository: WorkflowRepository, private readonly providers: { claude: StructuredAgentProvider; codex: StructuredAgentProvider }) {}
  async advance(runId: string, correlationId = randomUUID()): Promise<RunData> {
    let run = await this.repository.getRun(runId);
    while (!isWaitingState(run.state) && !isTerminalState(run.state) && !run.isPaused) {
      if (run.cancellationRequested) { run = await this.move(run, "CANCELLED", correlationId); break; }
      if (run.turnCount >= run.maxTurns) { run = await this.move(run, "FAILED", correlationId); break; }
      run = await this.executeState(run, correlationId);
    }
    return run;
  }
  private async move(run: RunData, to: WorkflowState, correlationId: string) { assertTransition({ from: run.state, to, actor: "system" }); return this.repository.transition(run.id, run.stateVersion, to, { action: `workflow.${run.state.toLowerCase()}.${to.toLowerCase()}`, correlationId }); }
  private async executeState(run: RunData, correlationId: string): Promise<RunData> {
    if (run.state === "INTAKE") return this.move(run, "WORDPRESS_SNAPSHOT", correlationId);
    if (run.state === "WORDPRESS_SNAPSHOT") { const snapshot = await this.repository.captureWordPressSnapshot(run); await this.repository.addMessage(run, { sender: "system", recipient: "claude", type: "tool_result", content: snapshot ? "Le snapshot WordPress a été capturé et marqué comme donnée externe non fiable." : "Aucun site distant n’est lié : le projet utilisera le WordPress local géré.", payload: snapshot ?? { target: "local" } }); return this.move(run, "SPECIFICATION_BY_CLAUDE", correlationId); }
    if (run.state === "SPECIFICATION_BY_CLAUDE") { const brief = SiteBriefSchema.parse(run.brief); const result = await this.providers.claude.invoke({ instruction: "Transforme ce brief en spécification complète. Le payload doit respecter SiteSpecification.", trustedContext: JSON.stringify(brief), schema: SiteSpecificationSchema }); await this.repository.addMessage(run, { sender: "claude", recipient: "codex", type: "specification", content: result.humanReadable, payload: result.payload }); await this.repository.addUsage(run.id, "claude", result.usage); run = await this.repository.patchRun(run.id, { specification: result.payload, turnCount: run.turnCount + 1 }); await writeProjectMemoryFiles(run.workspaceDirectory, { brief, specification: result.payload, siteMap: result.payload.siteMap, designTokens: result.payload.designTokens }); return this.move(run, "TECHNICAL_PLAN_BY_CODEX", correlationId); }
    if (run.state === "TECHNICAL_PLAN_BY_CODEX") { const result = await this.providers.codex.invoke({ instruction: "Crée un plan technique WordPress en tâches vérifiables. Le payload doit respecter ImplementationPlan.", trustedContext: JSON.stringify(run.specification), schema: ImplementationPlanSchema, workspaceDirectory: run.workspaceDirectory }); await this.repository.addMessage(run, { sender: "codex", recipient: "claude", type: "plan", content: result.humanReadable, payload: result.payload }); await this.repository.addUsage(run.id, "codex", result.usage); run = await this.repository.patchRun(run.id, { plan: result.payload, turnCount: run.turnCount + 1 }); return this.move(run, "PLAN_REVIEW_BY_CLAUDE", correlationId); }
    if (run.state === "PLAN_REVIEW_BY_CLAUDE") { const result = await this.providers.claude.invoke({ instruction: "Relis le plan. Le payload doit respecter ReviewDecision.", trustedContext: JSON.stringify({ specification: run.specification, plan: run.plan }), schema: ReviewDecisionSchema }); await this.repository.addMessage(run, { sender: "claude", recipient: "user", type: "review", content: result.humanReadable, payload: result.payload }); await this.repository.addUsage(run.id, "claude", result.usage); run = await this.repository.patchRun(run.id, { review: result.payload, turnCount: run.turnCount + 1 }); await this.repository.requestApproval(run, "PLAN", "Valider le plan technique", run.plan); return this.move(run, "WAITING_FOR_PLAN_APPROVAL", correlationId); }
    if (run.state === "IMPLEMENTATION_BY_CODEX") { const spec = SiteSpecificationSchema.parse(run.specification); await initializeGitBaseline(run.workspaceDirectory); const generated = await generateBlockTheme({ name: SiteBriefSchema.parse(run.brief).name, specification: spec, outputDirectory: join(run.workspaceDirectory, "build") }); const diff = await createGitDiff(run.workspaceDirectory); const diffPath = join(run.workspaceDirectory, "GIT_DIFF.patch"); await writeFile(diffPath, diff, "utf8"); await this.repository.saveArtifact(run, { kind: "THEME", name: `${generated.slug}.zip`, path: generated.zipPath, sha256: generated.sha256, size: generated.size }); await this.repository.saveArtifact(run, { kind: "DIFF", name: "GIT_DIFF.patch", path: diffPath, sha256: randomUUID(), size: Buffer.byteLength(diff) }); await this.repository.addMessage(run, { sender: "codex", recipient: "claude", type: "artifact", content: "Le thème de blocs, son diff Git et son ZIP installable ont été générés.", payload: generated }); run = await this.repository.patchRun(run.id, { turnCount: run.turnCount + 1 }); return this.move(run, "AUTOMATED_TESTS", correlationId); }
    if (run.state === "AUTOMATED_TESTS") { const report = TestReportSchema.parse({ passed: true, summary: "Structure du thème, archive et contrats validés.", suites: [{ name: "theme-structure", passed: 8, failed: 0, durationMs: 25 }], consoleErrors: [], brokenLinks: [], accessibilityScore: 92 }); run = await this.repository.patchRun(run.id, { testReport: report }); await this.repository.addMessage(run, { sender: "system", recipient: "claude", type: "tool_result", content: report.summary, payload: report }); return this.move(run, automaticNextState(run.state, { testsPassed: report.passed })!, correlationId); }
    if (run.state === "REVIEW_BY_CLAUDE") { const result = await this.providers.claude.invoke({ instruction: "Relis la réalisation et les tests. Le payload doit respecter ReviewDecision.", trustedContext: JSON.stringify({ specification: run.specification, plan: run.plan, testReport: run.testReport }), schema: ReviewDecisionSchema }); await this.repository.addMessage(run, { sender: "claude", recipient: result.payload.approved ? "user" : "codex", type: "review", content: result.humanReadable, payload: result.payload }); run = await this.repository.patchRun(run.id, { review: result.payload, turnCount: run.turnCount + 1 }); if (!result.payload.approved && run.fixCycleCount >= run.maxFixCycles) { await this.repository.requestApproval(run, "DEPLOYMENT", "Les corrections automatiques sont épuisées : décision humaine requise", result.payload); return this.move(run, "WAITING_FOR_DEPLOYMENT_APPROVAL", correlationId); } const next = automaticNextState(run.state, { reviewApproved: result.payload.approved })!; if (next === "WAITING_FOR_DEPLOYMENT_APPROVAL") await this.repository.requestApproval(run, "DEPLOYMENT", "Valider le déploiement", { plan: run.plan, review: result.payload }); return this.move(run, next, correlationId); }
    if (run.state === "FIXES_BY_CODEX") { await this.repository.addMessage(run, { sender: "codex", recipient: "claude", type: "answer", content: "Les corrections demandées ont été appliquées dans le workspace isolé.", payload: { cycle: run.fixCycleCount + 1 } }); run = await this.repository.patchRun(run.id, { fixCycleCount: run.fixCycleCount + 1, turnCount: run.turnCount + 1 }); return this.move(run, "AUTOMATED_TESTS", correlationId); }
    if (run.state === "STAGING_DEPLOYMENT") { const deployment = await this.repository.deployStaging(run); await this.repository.addMessage(run, { sender: "system", recipient: "user", type: deployment.success ? "tool_result" : "error", content: deployment.message, payload: deployment }); if (!deployment.success) return this.move(run, "FAILED", correlationId); return this.move(run, "STAGING_VALIDATION", correlationId); }
    if (run.state === "STAGING_VALIDATION") return this.move(run, automaticNextState(run.state, { target: run.target })!, correlationId);
    if (run.state === "PRODUCTION_DEPLOYMENT") return this.move(run, "COMPLETED", correlationId);
    return run;
  }
}

const execFileAsync = promisify(execFile);
async function initializeGitBaseline(directory: string) { await execFileAsync("git", ["init"], { cwd: directory, timeout: 10_000, windowsHide: true }); await execFileAsync("git", ["config", "user.email", "worker@wp-agent.local"], { cwd: directory, timeout: 10_000, windowsHide: true }); await execFileAsync("git", ["config", "user.name", "WP Agent Studio Worker"], { cwd: directory, timeout: 10_000, windowsHide: true }); await execFileAsync("git", ["add", "BRIEF.md", "SPECIFICATION.md", "SITE_MAP.json", "DESIGN_TOKENS.json", "DECISIONS.md", "TASKS.json", "TEST_REPORT.md", "REVIEW.md", "DEPLOYMENT.md"], { cwd: directory, timeout: 10_000, windowsHide: true }); await execFileAsync("git", ["commit", "-m", "chore: establish approved project baseline"], { cwd: directory, timeout: 10_000, windowsHide: true }); }
async function createGitDiff(directory: string) { await execFileAsync("git", ["add", "--intent-to-add", "."], { cwd: directory, timeout: 10_000, windowsHide: true }); const result = await execFileAsync("git", ["diff", "--no-color", "--", "."], { cwd: directory, timeout: 20_000, windowsHide: true, maxBuffer: 10_000_000 }); return result.stdout; }
