import { z } from "zod";
import { db } from "@wp-agent-studio/database";
import { encryptSecret } from "@wp-agent-studio/security";
import { RestWordPressConnector } from "@wp-agent-studio/wordpress";
import { WordPressCredentialsSchema } from "@wp-agent-studio/shared";
import { route, ok } from "@/lib/http";
const createSchema=WordPressCredentialsSchema.extend({name:z.string().min(2).max(100),allowPrivateNetwork:z.boolean().default(false)});
export const GET=route(async(_request,{session})=>ok(await db.wordPressSite.findMany({where:{workspaceId:session.workspaceId,deletedAt:null},select:{id:true,name:true,url:true,isLocal:true,lastConnectionStatus:true,createdAt:true},orderBy:{createdAt:"desc"}})),{permission:"site:read"});
export const POST=route(async(request,{session})=>{const input=createSchema.parse(await request.json());const allowPrivate=input.allowPrivateNetwork&&process.env.ENABLE_PRIVATE_NETWORK_TARGETS==="true";const connector=new RestWordPressConnector(input,{allowPrivate,production:process.env.NODE_ENV==="production"});const tested=await connector.testConnection();const encrypted=encryptSecret({url:input.url,username:input.username,applicationPassword:input.applicationPassword});const site=await db.$transaction(async(tx)=>{const secret=await tx.integrationSecret.upsert({where:{workspaceId_kind_label:{workspaceId:session.workspaceId,kind:"WORDPRESS",label:input.url}},update:{...encrypted,revokedAt:null},create:{workspaceId:session.workspaceId,kind:"WORDPRESS",label:input.url,...encrypted}});return tx.wordPressSite.upsert({where:{workspaceId_url:{workspaceId:session.workspaceId,url:input.url.replace(/\/$/,"")}},update:{name:input.name,secretId:secret.id,lastConnectionStatus:"connected",allowPrivateNetwork:allowPrivate,version:{increment:1}},create:{workspaceId:session.workspaceId,secretId:secret.id,name:input.name,url:input.url.replace(/\/$/,""),lastConnectionStatus:"connected",allowPrivateNetwork:allowPrivate}})});return ok({site:{id:site.id,name:site.name,url:site.url},connection:tested},201)},{permission:"site:write",csrf:true});
